/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sixnations;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Insets;
import java.net.URI;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Wayne Hartigan
 */
public class CardiffGUI extends javax.swing.JFrame {

    /**
     * Creates new form CardiffGUI
     */
    public CardiffGUI() {
        initComponents();
        JFrame temp = new JFrame();
        temp.pack();
        Insets insets = temp.getInsets();
        temp = null;
        this.setSize(new Dimension(insets.left + insets.right + 1120,
                insets.top + insets.bottom + 600));
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapBtn = new javax.swing.JButton();
        tourismHead = new javax.swing.JLabel();
        subHeader = new javax.swing.JLabel();
        tour1 = new javax.swing.JButton();
        tour2 = new javax.swing.JButton();
        tour3 = new javax.swing.JButton();
        tour4 = new javax.swing.JButton();
        tour5 = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();
        logoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mapBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\Cardiff.jpg")); // NOI18N
        mapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mapBtn);
        mapBtn.setBounds(30, 80, 710, 470);

        tourismHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tourismHead.setForeground(new java.awt.Color(255, 255, 255));
        tourismHead.setText("Cardiff Tourism Page");
        getContentPane().add(tourismHead);
        tourismHead.setBounds(580, 20, 274, 70);

        subHeader.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        subHeader.setForeground(new java.awt.Color(255, 255, 255));
        subHeader.setText("Popular Tourist Attractions:");
        getContentPane().add(subHeader);
        subHeader.setBounds(820, 120, 260, 60);

        tour1.setBackground(new java.awt.Color(255, 0, 51));
        tour1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour1.setForeground(new java.awt.Color(255, 255, 255));
        tour1.setText("Cardiff Stadium House");
        tour1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour1ActionPerformed(evt);
            }
        });
        getContentPane().add(tour1);
        tour1.setBounds(830, 230, 230, 17);

        tour2.setBackground(new java.awt.Color(255, 0, 51));
        tour2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour2.setForeground(new java.awt.Color(255, 255, 255));
        tour2.setText("Wales National War Memorial");
        tour2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour2ActionPerformed(evt);
            }
        });
        getContentPane().add(tour2);
        tour2.setBounds(830, 280, 230, 17);

        tour3.setBackground(new java.awt.Color(255, 0, 51));
        tour3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour3.setForeground(new java.awt.Color(255, 255, 255));
        tour3.setText("Roald Dahl Plass");
        tour3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour3ActionPerformed(evt);
            }
        });
        getContentPane().add(tour3);
        tour3.setBounds(830, 330, 230, 17);

        tour4.setBackground(new java.awt.Color(255, 0, 51));
        tour4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour4.setForeground(new java.awt.Color(255, 255, 255));
        tour4.setText("Wales Millennium Centre");
        tour4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour4ActionPerformed(evt);
            }
        });
        getContentPane().add(tour4);
        tour4.setBounds(830, 380, 230, 17);

        tour5.setBackground(new java.awt.Color(255, 0, 51));
        tour5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour5.setForeground(new java.awt.Color(255, 255, 255));
        tour5.setText("Caerphilly");
        tour5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour5ActionPerformed(evt);
            }
        });
        getContentPane().add(tour5);
        tour5.setBounds(830, 430, 230, 17);

        menuButton.setBackground(new java.awt.Color(255, 0, 51));
        menuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Main Menu");
        menuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton);
        menuButton.setBounds(930, 493, 186, 78);

        backgroundPanel.setBackground(new java.awt.Color(255, 0, 51));
        backgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backgroundPanel.setLayout(null);

        logoBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\Welsh_Rugby_Union_logo.svg.png")); // NOI18N
        logoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(logoBtn);
        logoBtn.setBounds(890, 10, 80, 100);

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, 0, 1120, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapBtnActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Cardiff,+UK/@51.5023267,-3.2696207,12z/data=!3m1!4b1!4m5!3m4!1s0x486e02d434ec53f5:0x143406db6586670e!8m2!3d51.481581!4d-3.17909?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mapBtnActionPerformed

    private void tour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour1ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Cardiff+Stadium+House/@51.5023267,-3.2696207,12z/data=!4m5!3m4!1s0x486e1cb1eae0a879:0xab08b83ebfa79e17!8m2!3d51.4784162!4d-3.1800458?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour1ActionPerformed

    private void tour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour2ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Wales+National+War+Memorial/@51.4865546,-3.1827103,17z/data=!3m1!4b1!4m5!3m4!1s0x486e1cbb6ce42d2b:0xbaf0532c0b03f493!8m2!3d51.4865513!4d-3.1805216?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour2ActionPerformed

    private void tour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour3ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Roald+Dahl+Plass/@51.4640229,-3.1662831,17z/data=!3m1!4b1!4m5!3m4!1s0x486e033707ac09f1:0xface15025d2f1488!8m2!3d51.4640196!4d-3.1640944?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour3ActionPerformed

    private void tour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour4ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Wales+Millennium+Centre/@51.4640229,-3.1662831,17z/data=!4m5!3m4!1s0x486e0336fb9949d1:0xb21b216518da85c6!8m2!3d51.4648421!4d-3.163183?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour4ActionPerformed

    private void tour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour5ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Caerphilly+Castle/@51.5760923,-3.2224377,17z/data=!3m1!4b1!4m5!3m4!1s0x486e194782afe35d:0xce745b13000b5cbf!8m2!3d51.576089!4d-3.220249?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour5ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void logoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoBtnActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.wru.co.uk");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_logoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardiffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardiffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardiffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardiffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardiffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton logoBtn;
    private javax.swing.JButton mapBtn;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel subHeader;
    private javax.swing.JButton tour1;
    private javax.swing.JButton tour2;
    private javax.swing.JButton tour3;
    private javax.swing.JButton tour4;
    private javax.swing.JButton tour5;
    private javax.swing.JLabel tourismHead;
    // End of variables declaration//GEN-END:variables
}
