/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sixnations;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Insets;
import java.net.URI;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Wayne Hartigan
 */
public class DublinGUI extends javax.swing.JFrame {

    /**
     * Creates new form DublinGUI
     */
    public DublinGUI() {
        initComponents();
        JFrame temp = new JFrame();
        temp.pack();
        Insets insets = temp.getInsets();
        temp = null;
        this.setSize(new Dimension(insets.left + insets.right + 1120,
                insets.top + insets.bottom + 600));
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton = new javax.swing.JButton();
        tourismHead = new javax.swing.JLabel();
        subHeader = new javax.swing.JLabel();
        tour1 = new javax.swing.JButton();
        tour2 = new javax.swing.JButton();
        tour3 = new javax.swing.JButton();
        tour4 = new javax.swing.JButton();
        tour5 = new javax.swing.JButton();
        mapBtn = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 159, 130));
        getContentPane().setLayout(null);

        menuButton.setBackground(new java.awt.Color(42, 159, 130));
        menuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Main Menu");
        menuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton);
        menuButton.setBounds(930, 493, 186, 78);

        tourismHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tourismHead.setForeground(new java.awt.Color(255, 255, 255));
        tourismHead.setText("Dublin Tourism Page");
        getContentPane().add(tourismHead);
        tourismHead.setBounds(580, 20, 274, 70);

        subHeader.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        subHeader.setForeground(new java.awt.Color(255, 255, 255));
        subHeader.setText("Popular Tourist Attractions:");
        getContentPane().add(subHeader);
        subHeader.setBounds(820, 120, 260, 60);

        tour1.setBackground(new java.awt.Color(42, 159, 130));
        tour1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour1.setForeground(new java.awt.Color(255, 255, 255));
        tour1.setText("Aviva Stadium");
        tour1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour1ActionPerformed(evt);
            }
        });
        getContentPane().add(tour1);
        tour1.setBounds(830, 230, 230, 17);

        tour2.setBackground(new java.awt.Color(42, 159, 130));
        tour2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour2.setForeground(new java.awt.Color(255, 255, 255));
        tour2.setText("Dublin Zoo");
        tour2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour2ActionPerformed(evt);
            }
        });
        getContentPane().add(tour2);
        tour2.setBounds(830, 280, 230, 17);

        tour3.setBackground(new java.awt.Color(42, 159, 130));
        tour3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour3.setForeground(new java.awt.Color(255, 255, 255));
        tour3.setText("Temple Bar");
        tour3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour3ActionPerformed(evt);
            }
        });
        getContentPane().add(tour3);
        tour3.setBounds(830, 330, 230, 17);

        tour4.setBackground(new java.awt.Color(42, 159, 130));
        tour4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour4.setForeground(new java.awt.Color(255, 255, 255));
        tour4.setText("O' Connel Street");
        tour4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour4ActionPerformed(evt);
            }
        });
        getContentPane().add(tour4);
        tour4.setBounds(830, 380, 230, 17);

        tour5.setBackground(new java.awt.Color(42, 159, 130));
        tour5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour5.setForeground(new java.awt.Color(255, 255, 255));
        tour5.setText("Croke Park");
        tour5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour5ActionPerformed(evt);
            }
        });
        getContentPane().add(tour5);
        tour5.setBounds(830, 430, 230, 17);

        mapBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\Dublin.jpg")); // NOI18N
        mapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mapBtn);
        mapBtn.setBounds(30, 80, 710, 470);

        backgroundPanel.setBackground(new java.awt.Color(42, 159, 130));
        backgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backgroundPanel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\126.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton2);
        jButton2.setBounds(890, 30, 70, 80);

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, 0, 1120, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void tour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour4ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/1+O'Connell+Street+Upper,+North+City,+Dublin/@53.349925,-6.2623661,17z/data=!3m1!4b1!4m5!3m4!1s0x48670e843b9cd1d9:0xb343a54d5701673d!8m2!3d53.3499218!4d-6.2601721");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour4ActionPerformed

    private void tour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour1ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Aviva+Stadium/@53.335235,-6.2306509,17z/data=!3m1!4b1!4m5!3m4!1s0x48670ec268eb8af9:0xe37e998e72032668!8m2!3d53.3352318!4d-6.228457");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour1ActionPerformed

    private void mapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapBtnActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Dublin/@53.3244427,-6.3861295,11z/data=!3m1!4b1!4m5!3m4!1s0x48670e80ea27ac2f:0xa00c7a9973171a0!8m2!3d53.3498053!4d-6.2603097");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mapBtnActionPerformed

    private void tour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour2ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Dublin+Zoo/@53.3561967,-6.3074838,17z/data=!3m1!4b1!4m5!3m4!1s0x48670c4b4afd1245:0x8aa7e3087b6a1b88!8m2!3d53.3561935!4d-6.3052898");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour2ActionPerformed

    private void tour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour3ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Temple+Bar,+Dublin/@53.3454357,-6.266874,17z/data=!3m1!4b1!4m5!3m4!1s0x48670e9cb559ea73:0x2600c7a819c83012!8m2!3d53.3449379!4d-6.2674731");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour3ActionPerformed

    private void tour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour5ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Croke+Park/@53.3607152,-6.2534029,17z/data=!3m1!4b1!4m5!3m4!1s0x48670e639264f995:0xe51347860e88b45f!8m2!3d53.360712!4d-6.2512089");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DublinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DublinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DublinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DublinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DublinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton mapBtn;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel subHeader;
    private javax.swing.JButton tour1;
    private javax.swing.JButton tour2;
    private javax.swing.JButton tour3;
    private javax.swing.JButton tour4;
    private javax.swing.JButton tour5;
    private javax.swing.JLabel tourismHead;
    // End of variables declaration//GEN-END:variables
}
