/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sixnations;

import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFrame;

/**
 *
 * @author x16325901
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private User currentUser;

    public Login() {
        initComponents();
        JFrame temp = new JFrame();
        temp.pack();
        Insets insets = temp.getInsets();
        temp = null;
        this.setSize(new Dimension(insets.left + insets.right + 590,
                insets.top + insets.bottom + 380));
        this.setVisible(true);
        this.setResizable(false);
        currentUser = new User();
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jtxtUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnNewUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtCountry = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        trophyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(67, 19, 95));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setLayout(null);

        jbtnLogin.setBackground(new java.awt.Color(67, 19, 95));
        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLogin.setText("Login");
        jbtnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin);
        jbtnLogin.setBounds(182, 229, 90, 60);

        jbtnReset.setBackground(new java.awt.Color(67, 19, 95));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset);
        jbtnReset.setBounds(300, 230, 80, 60);

        jbtnExit.setBackground(new java.awt.Color(67, 19, 95));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit);
        jbtnExit.setBounds(410, 230, 80, 60);
        jPanel1.add(jtxtUserName);
        jtxtUserName.setBounds(230, 70, 160, 20);
        jPanel1.add(jPassword);
        jPassword.setBounds(230, 112, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 70, 74, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(112, 112, 72, 17);

        jbtnNewUser.setBackground(new java.awt.Color(67, 19, 95));
        jbtnNewUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNewUser.setText("New User");
        jbtnNewUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNewUser);
        jbtnNewUser.setBounds(44, 229, 120, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Country:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(112, 162, 62, 17);
        jPanel1.add(jtxtCountry);
        jtxtCountry.setBounds(230, 162, 160, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Six Nations Tourist App Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 280, 32);

        trophyBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\ojm3WBmS_400x400.jpg")); // NOI18N
        trophyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(trophyBtn);
        trophyBtn.setBounds(420, 70, 140, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -1, 590, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtUserName.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed

        String password;
        String username;
        String country;
        boolean login = false;

        FileInputStream istream;
        ObjectInputStream ostream;

        try {
            istream = new FileInputStream(jtxtUserName.getText() + "info.data");
            ostream = new ObjectInputStream(istream);
            User us = (User) ostream.readObject();

            username = us.getName();
            password = us.getPassword();
            country = us.getCountry();

            if ((username.equalsIgnoreCase(jtxtUserName.getText())) && (password.equalsIgnoreCase(jPassword.getText())) && (country.equalsIgnoreCase(jtxtCountry.getText()))) {
                jtxtUserName.setText(null);
                jPassword.setText(null);
                jtxtCountry.setText(null);
                systemExit();
                login = true;

            } else {

                System.out.println(us.getName());
                System.out.println(us.getPassword());
                System.out.println(us.getCountry());
                login = false;

            }
            if (login == true) {
                switch (us.getCountry()) {
                    case "Ireland":
                        IrelandGUI irl = new IrelandGUI();
                        irl.setVisible(true);
                        break;
                    case "England":
                        EnglandGUI eng = new EnglandGUI();
                        eng.setVisible(true);
                        break;
                    case "France":
                        FranceGUI fra = new FranceGUI();
                        fra.setVisible(true);
                        break;
                    case "Wales":
                        WalesGUI wal = new WalesGUI();
                        wal.setVisible(true);
                        break;
                    case "Scotland":
                        ScotlandGUI scot = new ScotlandGUI();
                        scot.setVisible(true);
                        break;
                    case "Italy":
                        ItalyGUI ita = new ItalyGUI();
                        ita.setVisible(true);
                        break;
                }
            } else {

                JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
                jPassword.setText(null);
                jtxtUserName.setText(null);

            }
            us = currentUser;

        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);

        }


    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewUserActionPerformed
        String username = jtxtUserName.getText();
        String password = jPassword.getText();
        String country = jtxtCountry.getText();

        User newUser = new User();
        //userList = new ArrayList<User>();
        //userList.add(newUser);

        newUser.setName(username);
        newUser.setPassword(password);
        newUser.setCountry(country);

        File userf;
        FileOutputStream fstream;
        ObjectOutputStream ostream;

        try {
            userf = new File(username + "info.data");
            fstream = new FileOutputStream(userf);
            ostream = new ObjectOutputStream(fstream);

            ostream.writeObject(newUser);
            ostream.close();
        } catch (IOException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jbtnNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnNewUser;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtCountry;
    private javax.swing.JTextField jtxtUserName;
    private javax.swing.JButton trophyBtn;
    // End of variables declaration//GEN-END:variables

    private void systemExit() {
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }

}
