/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sixnations;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Insets;
import java.net.URI;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Wayne Hartigan
 */
public class ParisGUI extends javax.swing.JFrame {

    /**
     * Creates new form ParisGUI
     */
    public ParisGUI() {
        initComponents();
        JFrame temp = new JFrame();
        temp.pack();
        Insets insets = temp.getInsets();
        temp = null;
        this.setSize(new Dimension(insets.left + insets.right + 1120,
                insets.top + insets.bottom + 600));
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapBtn = new javax.swing.JButton();
        tourismHead = new javax.swing.JLabel();
        subHeader = new javax.swing.JLabel();
        tour1 = new javax.swing.JButton();
        tour2 = new javax.swing.JButton();
        tour3 = new javax.swing.JButton();
        tour4 = new javax.swing.JButton();
        tour5 = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mapBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\Paris.jpg")); // NOI18N
        mapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mapBtn);
        mapBtn.setBounds(30, 80, 710, 420);

        tourismHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tourismHead.setForeground(new java.awt.Color(255, 255, 255));
        tourismHead.setText("Paris Tourism Page");
        getContentPane().add(tourismHead);
        tourismHead.setBounds(580, 20, 274, 70);

        subHeader.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        subHeader.setForeground(new java.awt.Color(255, 255, 255));
        subHeader.setText("Popular Tourist Attractions:");
        getContentPane().add(subHeader);
        subHeader.setBounds(820, 120, 260, 60);

        tour1.setBackground(new java.awt.Color(0, 82, 156));
        tour1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour1.setForeground(new java.awt.Color(255, 255, 255));
        tour1.setText("Eiffel Tower");
        tour1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        tour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour1ActionPerformed(evt);
            }
        });
        getContentPane().add(tour1);
        tour1.setBounds(830, 230, 230, 17);

        tour2.setBackground(new java.awt.Color(0, 82, 156));
        tour2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour2.setForeground(new java.awt.Color(255, 255, 255));
        tour2.setText("Place de la Concorde");
        tour2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        tour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour2ActionPerformed(evt);
            }
        });
        getContentPane().add(tour2);
        tour2.setBounds(830, 280, 230, 17);

        tour3.setBackground(new java.awt.Color(0, 82, 156));
        tour3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour3.setForeground(new java.awt.Color(255, 255, 255));
        tour3.setText("Sainte-Chapelle");
        tour3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        tour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour3ActionPerformed(evt);
            }
        });
        getContentPane().add(tour3);
        tour3.setBounds(830, 330, 230, 17);

        tour4.setBackground(new java.awt.Color(0, 82, 156));
        tour4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour4.setForeground(new java.awt.Color(255, 255, 255));
        tour4.setText("Conciergerie");
        tour4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        tour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour4ActionPerformed(evt);
            }
        });
        getContentPane().add(tour4);
        tour4.setBounds(830, 380, 230, 17);

        tour5.setBackground(new java.awt.Color(0, 82, 156));
        tour5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tour5.setForeground(new java.awt.Color(255, 255, 255));
        tour5.setText("Panthéon");
        tour5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        tour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour5ActionPerformed(evt);
            }
        });
        getContentPane().add(tour5);
        tour5.setBounds(830, 430, 230, 17);

        menuButton.setBackground(new java.awt.Color(0, 82, 156));
        menuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Main Menu");
        menuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 26, 49)));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton);
        menuButton.setBounds(930, 493, 186, 78);

        backgroundPanel.setBackground(new java.awt.Color(0, 82, 156));
        backgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backgroundPanel.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy Sheehy\\Desktop\\Year 2 Semester 1\\Programming\\Project\\Images\\Fédération_Française_de_Rugby_logo.svg.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton2);
        jButton2.setBounds(890, 20, 110, 90);

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, 0, 1120, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapBtnActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Paris,+France/@48.8589506,2.2768486,12z/data=!3m1!4b1!4m5!3m4!1s0x47e66e1f06e2b70f:0x40b82c3688c9460!8m2!3d48.856614!4d2.3522219?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mapBtnActionPerformed

    private void tour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour1ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Eiffel+Tower/@48.8603197,2.3087993,13z/data=!4m8!1m2!2m1!1stourist+attractions+near+Paris,+France!3m4!1s0x47e66e2964e34e2d:0x8ddca9ee380ef7e0!8m2!3d48.8583701!4d2.2944813");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour1ActionPerformed

    private void tour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour2ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Place+de+la+Concorde/@48.8656366,2.3190417,17z/data=!3m1!4b1!4m5!3m4!1s0x47e66fcd61ae0a01:0x18030de10e25ab2c!8m2!3d48.8656331!4d2.3212357?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour2ActionPerformed

    private void tour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour3ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Sainte-Chapelle/@48.8603197,2.3087993,13z/data=!4m8!1m2!2m1!1stourist+attractions+near+Paris,+France!3m4!1s0x47e66e1fd8767d47:0x33f441f9dc242768!8m2!3d48.85542!4d2.344987");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour3ActionPerformed

    private void tour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour4ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Conciergerie/@48.8560149,2.3433013,17z/data=!3m1!4b1!4m5!3m4!1s0x47e66e1fd8767d47:0x90ca4b466cb6316a!8m2!3d48.8560114!4d2.3454953?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour4ActionPerformed

    private void tour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour5ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.google.ie/maps/place/Panth%C3%A9on/@48.8462253,2.3442198,17z/data=!3m1!4b1!4m5!3m4!1s0x47e671e7d297c973:0xe5eb004f23a758!8m2!3d48.8462218!4d2.3464138?hl=en");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tour5ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                URL avivaurl = new URL("https://www.ffr.fr");
                URI uri = avivaurl.toURI();
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParisGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton mapBtn;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel subHeader;
    private javax.swing.JButton tour1;
    private javax.swing.JButton tour2;
    private javax.swing.JButton tour3;
    private javax.swing.JButton tour4;
    private javax.swing.JButton tour5;
    private javax.swing.JLabel tourismHead;
    // End of variables declaration//GEN-END:variables
}
